# This configuration is intended for development purpose
name: bytechef-monitoring
services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000' # UI
      - '4317:4317'
      - '4318:4318'
